#
# JBZoo Toolbox - Toolbox-CI
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Toolbox-CI
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Toolbox-CI
#

name: Test Output

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Testinputs
        run: |
            echo "::group::My title::something"
            echo "::debug::Set the Octocat variable"
            echo "::warning file=Makefile,line=14,col=9::JBZoo\PHPUnit\ExampleTest->testCompareString%0AFailed asserting that two strings are identical.%0A--- Expected%0A+++ Actual%0A@@ @@%0A-'132'%0A+'123'%0A%0Avendor/jbzoo/phpunit/src/functions/aliases.php:197%0Atests/ExampleTest.php:103"
            echo "::error file=README.md,line=47,col=15::JBZoo\PHPUnit\ExampleTest::testCompareString%0AFailed asserting that two strings are identical.%0A--- Expected%0A+++ Actual%0A@@ @@%0A-'132'%0A+'123'%0A%0Avendor/jbzoo/phpunit/src/functions/aliases.php:197%0Atests/ExampleTest.php:103"
            echo "::endgroup::"
